# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa3f92557a85cb0bbd13ffaa0dcf16a00d49732979ae31595ae37a769916f8a8de61808cebdc64bd79973bc3f97944da2a8d6045f6ca0923ab194c7225d25e67

test:
  secret_key_base: 704dfc2ea59cdfa5904672afd53e22321eff9557de043d669c5916087c55010fdf05d18c44e8d6083567d43ea87bb8d74a6e2ea432958d303a804b8d1b9abbdc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
